### ISSUE TITLE
Effect List no show

### ISSUE THREAD

**Issue by ThAnKm3Lat3R** [bruhautomation/ESP-MQTT-JSON-Digital-LEDs#55]
Effect List is not showing up in Home Assistant with the code that is provided. I can see the Input Number, Automation, and Light Boxes but no section for effects.

**Comment by Makr91** [comment]
Can you show us your entire .yaml configuration

**Comment by ThAnKm3Lat3R** [comment]
Sorry for the delayed response....


[configuration.txt](https://github.com/bruhautomation/ESP-MQTT-JSON-Digital-LEDs/files/1425469/configuration.txt)

**Comment by derspion318** [comment]
I too am missing the effects list drop down.

```
  - platform: mqtt_json
    name: "Porch Strip"
    state_topic: "home/porch"
    command_topic: "home/porch/set"
    effect: true
    effect_list:
      - bpm
      - candy cane
      - confetti
      - cyclon rainbow
      - dots
      - fire
      - glitter
      - juggle
      - lightning
      - noise
      - police all
      - police one
      - rainbow
      - rainbow with glitter
      - ripple
      - sinelon
      - solid
      - twinkle
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
```


![image](https://user-images.githubusercontent.com/24965344/32406320-674eeca0-c144-11e7-91e5-c728d916795a.png)

![image](https://user-images.githubusercontent.com/24965344/32406329-76708de2-c144-11e7-9921-bb9984abc594.png)
