### ISSUE TITLE
HA Automation question

### ISSUE THREAD

**Issue by pcdiks** [bruhautomation/ESP-MQTT-JSON-Digital-LEDs#74]
I'm trying to use a Xiaomi Cube to change the effect when I shake the cube. To do that, I created the following automation:
`
- id: ledstrip_shake
  alias: Xiaomi Cube - Shake
  initial_state: false
  hide_entity: true
  trigger:
  - platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001100c4e
      action_type: shake_air
  action:
  - service: light.turn_on
    entity_id: light.led_strip
    data:
      "effect": "solid"
`

HA says that my config is valid, I can see the automation in the Automation Editor in the GUI as well. But it does not work. I think it has to do with the data part of the automation but I'm not sure. Could you give me some insights? 
The shaking part of the Xiaomi Cube is working by the way. I see the event in the logs but the action is not actived.

**Comment by Rawet** [comment]
I think the problem is entity_id is in the wrong position and the quotation marks, try removeing them and move entity_id inside "data".
My automations works just fine.

```
    - service: light.turn_on
      data: 
        entity_id: light.ledstripnamehere
        brightness: 255
        effect: solid
        color_name: red
```
